apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    name: app-service
    app: app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30008
  selector:
    app: app
    type: mvc
